### ISSUE TITLE
Trigger bot Bug

### ISSUE THREAD

**Issue by CKH0** [0x000cb/otc#24]
https://imgur.com/a/PmEWaLj
I think OT calls a bunch of functions over and over again is reasonable. Like checking the player location .etc(I have no idea about coding. All this is my assumption)
But your new update maybe breaks it :thinking:
![image](https://user-images.githubusercontent.com/18748818/79414998-b71fc000-7fde-11ea-9813-6919da44e7e8.png)

**Comment by cptmacp** [comment]
if you used the latest source and compiled after this [commit](https://github.com/0x000cb/otc/commit/16a42dcbc053c3a85222b65883d213ec2b9de5fa)

then yes 


this breaks triggerbot , but prevent a crash from backtracking .

since he [mentioned](https://github.com/0x000cb/otc/commit/16a42dcbc053c3a85222b65883d213ec2b9de5fa#commitcomment-38518087) its a temporary fix

**Comment by 0x000cb** [comment]
Yes, I know this problem. This is due to the fact that I disabled the call to the function that receives / calls the virtual function (inside the SmthVectorProcessed function). To fix this, you need to understand the failure problem and why OT gets nullptr instead of the virtual address. I will try to figure it out later and release a fix update. The current fix is ​​now a temporary fix for crash.

**Comment by 0x000cb** [comment]
New magical fix in an hour.

**Comment by 0x000cb** [comment]
Complete. Re-Download release.

**Comment by cptmacp** [comment]
yay
