### ISSUE TITLE
купить бот

### ISSUE THREAD

**Issue by billythejew456** [0x000cb/otc#3]
бот покупки сломан, и поэтому альтернативный вариант в бот покупки но помимо этого его действительно хорошо спасибо

**Comment by 0x000cb** [comment]
Do not try to write in a language you do not know. Everyone knows how to use a translator. I will try to deal with the bot, but most likely I will just change this to just a bind.

**Comment by 0x000cb** [comment]
Hello again. I currently have the reverse BuyBotCmd function from OTCv2 (https://pastebin.com/ZdzeEx61). 

But I think it makes no sense to fix it right now. (Because source 2, according to Chinese sources, is scheduled for the 18th) 

Therefore, I will open this issue until the 18th, and it will already be visible there whether it is worth fixing it or still it makes sense to tackle OpenOTC.

**Comment by 0x000cb** [comment]
Resolved.
