### ISSUE TITLE
Unavailable settings in Deathmatch and Casual.

### ISSUE THREAD

**Issue by Tachyonator** [0x000cb/otc#38]
I have found that Legit anti-aim and fast crouch (and some other settings on the rage anti-aim and rage-bot) are not available for casual play.
Can this bug be fixed?

Best Regards

**Comment by 0x000cb** [comment]
What do you mean "Not available"? VAC Error?

**Comment by Tachyonator** [comment]
Hello, the functions disappear in the Cheat menu (I can´t select it). (only casual; Matchmaking and Dangerzone it works fine).
 

Gesendet: Dienstag, 28. April 2020 um 21:37 Uhr
Von: "0x000cb" <notifications@github.com>
An: "0x000cb/otc" <otc@noreply.github.com>
Cc: "Tachyonator" <waldesruh1928@gmx.de>, "Author" <author@noreply.github.com>
Betreff: Re: [0x000cb/otc] Unavailable settings in Deathmatch and Casual. (#38)


 

What do you mean "Not available"? VAC Error?

**Comment by 0x000cb** [comment]
Ah, maybe you're talking about Aimstep Valve servers. Yes, OT checks which server you are playing on, and if it is, for example, Valve Aimstep, it disables exploits because you can immediately get a VAC ban for them.

-----
I won’t fix it, maybe I’ll release a function that will disable the check, but to protect users this feature will be disabled, you will have to clone the repository yourself and enable this feature.
