### ISSUE TITLE
Hitbox override and hitchance/multipoint

### ISSUE THREAD

**Issue by KevinRommens** [0x000cb/otc#96]
So, whenever i turn on hitbox override (head only to make scout hit more) it sometimes doesn't shoot when the head is visible or it baims when head is visible. Same with multipoint, sometimes the cheat doesn't shoot when they are clearly being able to get hit (i have multipoint for body on 50%).

**Comment by 0x000cb** [comment]
Hit chances and multipoints are not my area of ​​activity, but I can still explain some points.

> So, whenever i turn on hitbox override (head only to make scout hit more) it sometimes doesn't shoot when the head is visible or it baims when head is visible.

Most likely this is due to a hitchance or because of a resolver that has already missed several times.

> Same with multipoint, sometimes the cheat doesn't shoot when they are clearly being able to get hit (i have multipoint for body on 50%).

It can also be caused by a hitchance, but most likely an exploit that was found recently. It allows you to make you unhittable for a couple of seconds.
